### PR TITLE
Fix the plugin.  Please publish

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by francois2metz** [comment]
Sounds good. Can you please squash commits?

**Comment by JohnMcLear** [comment]
Nah, it's good to go like this.

**Comment by francois2metz** [comment]
I did myself. Thanks for the contribution :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by JohnMcLear** [comment]
Np
----- Reply message -----

**Pull request closed without merging**
